In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3



'%.3f'

In [15]:
import numpy as np
%precision 3

data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print(data)
print(data.dtype)
print('dimension num: ', data.ndim)
print('element num: ', data.size)
print(data * 2)

data.sort()
print('after sorted: ', data)
data[::-1].sort()
print('after sorted: ', data)

print('Min: ', data.min())
print('Max: ', data.max())
print('Sum: ', data.sum())
print('Cum: ', data.cumsum())
print('Ratio: ', data.cumsum() / data.sum())

[ 9  2  3  4 10  6  7  8  1  5]
int64
dimension num:  1
element num:  10
[18  4  6  8 20 12 14 16  2 10]
after sorted:  [ 1  2  3  4  5  6  7  8  9 10]
after sorted:  [10  9  8  7  6  5  4  3  2  1]
Min:  1
Max:  10
Sum:  55
Cum:  [10 19 27 34 40 45 49 52 54 55]
Ratio:  [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [25]:
import numpy as np
%precision 3
import numpy.random as random

random.seed(10000)
rnd_data = random.randn(10)
print('10 random numbers array: ', rnd_data)

data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print(random.choice(data, 5))
print(random.choice(data, 5, replace=False))

10 random numbers array:  [-1.271  0.176 -0.296  0.327 -0.973  0.228 -0.819  0.107  0.975  0.082]
[8 1 5 3 4]
[ 1  2  3  4 10]


In [27]:
import numpy as np

N = 10**6
normal_data = [random.random() for _ in range(N)]

numpy_random_data = np.array(normal_data)

%timeit sum(normal_data)

%timeit np.sum(numpy_random_data)

3.74 ms ± 142 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
501 µs ± 121 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
