In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3



'%.3f'

In [15]:
import numpy as np
%precision 3

data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print(data)
print(data.dtype)
print('dimension num: ', data.ndim)
print('element num: ', data.size)
print(data * 2)

data.sort()
print('after sorted: ', data)
data[::-1].sort()
print('after sorted: ', data)

print('Min: ', data.min())
print('Max: ', data.max())
print('Sum: ', data.sum())
print('Cum: ', data.cumsum())
print('Ratio: ', data.cumsum() / data.sum())

[ 9  2  3  4 10  6  7  8  1  5]
int64
dimension num:  1
element num:  10
[18  4  6  8 20 12 14 16  2 10]
after sorted:  [ 1  2  3  4  5  6  7  8  9 10]
after sorted:  [10  9  8  7  6  5  4  3  2  1]
Min:  1
Max:  10
Sum:  55
Cum:  [10 19 27 34 40 45 49 52 54 55]
Ratio:  [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [25]:
import numpy as np
%precision 3
import numpy.random as random

random.seed(10000)
rnd_data = random.randn(10)
print('10 random numbers array: ', rnd_data)

data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print(random.choice(data, 5))
print(random.choice(data, 5, replace=False))

10 random numbers array:  [-1.271  0.176 -0.296  0.327 -0.973  0.228 -0.819  0.107  0.975  0.082]
[8 1 5 3 4]
[ 1  2  3  4 10]


In [2]:
import numpy as np

N = 10**6
normal_data = [random.random() for _ in range(N)]

numpy_random_data = np.array(normal_data)

%timeit sum(normal_data)

%timeit np.sum(numpy_random_data)

5.08 ms ± 130 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
542 µs ± 37.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
import numpy as np

print(np.arange(9))
array1 = np.arange(9).reshape(3, 3)
print(array1)
print(array1[0,:])
print(array1[:,0])

array2 = np.arange(9, 18).reshape(3, 3)
print(array2)
print(np.dot(array1, array2))
print(array1 * array2)
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[0 3 6]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# 練習問題 2-1
# 1から50までの自然数の和を計算し、最後の計算結果を表示する
# np.arrayで1から50までの配列を作り総和を求める
import numpy as np

nums = np.arange(1, 51)
print(nums)
print('total num: ', nums.sum())

# answer
data = np.array([i for i in range(1, 51)])
print(data.sum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
total num:  1275
1275


In [27]:
# 練習問題 2-2
# 標準正規分布に従う乱数を10個発生されて配列を作成
# 最小値・最大値・合計を求める

import numpy as np
import numpy.random as random

random.seed(1234567890)
rnd_data = random.randn(10)
print(rnd_data)
print('min:  ', rnd_data.min())
print('max: ', rnd_data.max())
print('sum: ', rnd_data.sum())

[ 1.34   1.738  1.499 -0.229  2.031  2.17   1.596 -0.769  0.566 -0.119]
min:   -0.7694515563516945
max:  2.1703249460565526
sum:  9.823247791780027


In [1]:
# 練習問題2-3
# 要素がすべて3の5x5の行列を作成
# 行列を2乗する計算を行う

import numpy as np

array1 = np.full([5, 5], 3, np.int64)
print(array1)
print(array1 ** 2)

# answer
print(array1.dot(array1))

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]


In [12]:
import numpy as np
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

matrix = np.array([[1,-1,-1], [-1,1,-1],[-1,-1,1]])
# 行列式
# See https://oguemon.com/study/linear-algebra/det-what/
# 行列式は、行列の特徴を表す指標の一つで、スカラー（数値）になる
# 数学的には、|A| det(A)のどちらかで表される
# 行列式は正方行列に対してのみ定義される
# 正方行列: 行要素数・列要素数が一致する行列、つまりn*nの行列を示す
print('deteminant')
print(linalg.det(matrix))

# 逆行列
# See https://oguemon.com/study/linear-algebra/matrix-regular/
# 類似概念 逆数 aに対する1/a
print('invert determinant')
print(linalg.inv(matrix))

# もとの行列と逆行列の積は単位行列
print(matrix.dot(linalg.inv(matrix)))

# 固有値・固有ベクトル
# See https://atarimae.biz/archives/24166
# 行列Aの固有ベクトルx = y倍されるだけで方向は変わらないベクトル
# 主成分分析に用いる
eig_value, eig_vector = linalg.eig(matrix)
print('eigenvalue')
print(eig_value)
print('eigenvalue vector')
print(eig_vector)

deteminant
-4.0
invert determinant
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eigenvalue
[-1.+0.j  2.+0.j  2.+0.j]
eigenvalue vector
[[ 0.57735027 -0.81649658  0.42755853]
 [ 0.57735027  0.40824829 -0.81618716]
 [ 0.57735027  0.40824829  0.38862863]]


In [23]:
from scipy.optimize import newton
from scipy.optimize import minimize_scalar

def myFunction(x):
    return (x**2 + 2*x + 1)

# ニュートン法
# See https://qiita.com/PlanetMeron/items/09d7eb204868e1a49f49
print(newton(myFunction, 0))

# 最小値
print(minimize_scalar(myFunction, method = 'Brent'))
def customFunc(x):
    return (3*x**2 + 5*x + 10)

print(minimize_scalar(customFunc, method = 'Golden'))

-0.9999999852953906
     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002
     fun: 7.916666666666666
    nfev: 44
     nit: 38
 success: True
       x: -0.8333333333333334


In [26]:
# 練習問題2-4

import numpy as np
import scipy.linalg as linalg

matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(linalg.det(matrix))

-12.000000000000002


In [30]:
# 練習問題2-5
# 2-4の逆行列・固有値・固有ベクトルを求める

import numpy as np
import scipy.linalg as linalg

matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(linalg.inv(matrix))
eig_value, eig_vector = linalg.eig(matrix)
print(eig_value)
print(eig_vector)


[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
[ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [36]:
# 練習問題2-6

from scipy.optimize import newton

def myFunc(x):
    return (x**3 + 2*x + 1)

print(newton(myFunc, 0))
print(myFunc(newton(myFunc, 0)))

-0.45339765151640365
3.3306690738754696e-16
